# Generated by Django 4.2.3 on 2023-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.AddField(
            model_name='account',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
