# Generated by Django 4.2.3 on 2023-07-24 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 18, 43, 435684)),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 20, 43, 435684)),
        ),
    ]
