# Generated by Django 4.2.3 on 2023-07-22 18:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. 11 character. digits only.', max_length=14, unique=True, validators=[core.validators.PhoneValidator()], verbose_name='phone number'),
        ),
    ]
