"""
Django settings for ShoesOnlineStore project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from os import getenv
from dotenv import load_dotenv

from django.contrib.messages import constants as messages

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # ["*"] if DEBUG else ['127.0.0.1']

# CORS engine configuration (django-cors-headers) :
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = ["http://0.0.0.0:8000",
                        "http://localhost:8000", "https://sandbox.zarinpal.com "]

CORS_ORIGIN_ALLOW_ALL = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'home.apps.HomeConfig',
    'core.apps.CoreConfig',
    'orders.apps.OrdersConfig',
    'shoes.apps.ShoesConfig',
    'accounts.apps.AccountsConfig',
    'otp.apps.OtpConfig',
    "ckeditor",
    'drf_spectacular',
    'django_celery_results',
    'django_celery_beat',

]
AUTHENTICATION_BACKENDS = [
    "accounts.backends.PhoneNumberBackend",
]


MAX_DIGITS = 20
DECIMAL_PLACES = 0
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'ShoesOnlineStore.urls'
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_COOKIE_SECURE = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.cart'
            ],
        },
    },
]

WSGI_APPLICATION = 'ShoesOnlineStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': getenv("NAME"),
        'USER': getenv("USER"),
        'PASSWORD': getenv("PASSWORD"),
        'HOST': getenv("HOST"),
        'PORT': getenv("PORT"),
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("accounts.authentication.LoginAuthentication",),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',

    "PAGE_SIZE": 3,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',]
}
SPECTACULAR_SETTINGS = {
    'TITLE': 'Shoes Online Shopping API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "statics/"
STATICFILES_DIRS = [
    BASE_DIR / "statics",
]


# STATIC_ROOT = os.path.join(BASE_DIR, "statics")
AUTH_USER_MODEL = 'accounts.Account'
SMS_API_KEY = getenv("SMS_API_KEY")

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-warning",
}
# SANDBOX MODE ZARRINPAL


SANDBOX = True

MERCHANT = getenv("MERCHANT")


# CELERY SETTINGS

CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'

CELERY_RESULT_BACKEND = 'django-db'

# CELERY BEAT
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# SMTP Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = 'r.nikookolah@gmail.com'
EMAIL_HOST_PASSWORD = getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = 'Celery <r.nikookolah@gmail.com>'


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'log/file.log',
        },
        "report": {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'log/report.log',
            "formatter": "verbose",

        }
    },
    'formatters': {
        'verbose': {
            'format': '{ "time": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s" }'
        },
    },
    'loggers': {
        # 'django': {
        #     'handlers': ['file'],
        #     'level': 'INFO',
        #     'propagate': False,
        # },

        'ShoesOnlineStore.orders': {
            'handlers': ['report'],
            'level': 'INFO',
        },
    },

}
# Django's SSL security configurations :
# REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
#     "rest_framework.renderers.JSONRenderer",)

# Https settings
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = "HTTP_X_FORWARDED_PROTO", "https"

# # HSTS settings
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_SECONDS = 86400

# # more security settings
# USE_X_FORWARDED_HOST = True
# SECURE_REFERRER_POLICY = "strict-origin"


# # Internationalization Configs:
# USE_TZ = True
# USE_L10 = True
# USE_L10N = True
# USE_I18N = True

# # Serving Configs:
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
# STATIC_URL = "/static/"
# STATIC_ROOT = BASE_DIR / "static/"

# # Basic Security Configs
# X_FRAME_OPTIONS = "SAMEORIGIN"
# SESSION_TIMEOUT = 24 * 60 * 60
# SESSION_COOKIE_AGE = 3 * 60 * 60
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# # Content Security Policy
# CSP_DEFAULT_SRC = "'none'",
# CSP_STYLE_SRC = "'self'",
# CSP_SCRIPT_SRC = "'self'",
# CSP_IMG_SRC = "'self'",
# CSP_FONT_SRC = "'self'",
