version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    networks:
      - main_net
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/app
    depends_on:
      - db
      # - redis
    expose:
      - "8000"
    networks:
      - main_net
    ports:
      - "8000:8000"
    restart: on-failure
  # redis:
  #   image: redis:alpine
  # celery:
  #   build: ./project
  #   command: celery -A core worker -l info
  #   volumes:
  #     - .:/usr/src/app/
  #   depends_on:
  #     - redis
  # celery-beat:
  #   build: .
  #   command: celery -A core beat -l info
  #   volumes:
  #     - .:/usr/src/app/
  #   environment:
  #     - DEBUG=1
  #   depends_on:
  #     - redis




volumes:
  postgres_data:


networks:
  main_net:


