# Generated by Django 4.2.3 on 2023-08-02 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sending_type', models.IntegerField(choices=[(1, ' تکس '), (2, '🚚 پست  '), (3, '🚖 تحویل در شهر')], default=2)),
                ('delivery_status', models.IntegerField(choices=[(0, 'لغو شده ❌'), (1, 'در انبار🚂'), (2, 'ارسال شده 🚛'), (3, 'تحویل داده شده ✔')], default=1)),
                ('tracking_code', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('self_receive', models.BooleanField(default=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(choices=[('thr', 'Tehran'), ('az-sh', 'Azarbayejan Sharghi'), ('az-gh', 'Azarbayejan Gharbi'), ('ard', 'Ardebil'), ('esf', 'Esfehan'), ('alb', 'Alborz'), ('ilm', 'Ilam'), ('bsh', 'Booshehr'), ('chm', 'Charmahal o Bakhtiari'), ('kh-j', 'Khorasan Jonobi'), ('kh-r', 'Khorasan Razavi'), ('kh-sh', 'Khorasan Shomali'), ('khz', 'Khoozestan'), ('znj', 'Zanjan'), ('smn', 'Semnan'), ('sbch', 'Sistan Baloochestan'), ('frs', 'Fars'), ('ghz', 'Ghazvin'), ('qom', 'Qom'), ('krd', 'Kordestan'), ('krm', 'Kerman'), ('kr-sh', 'Kerman Shah'), ('khb', 'Kohkilooye Boyer Ahmad'), ('gls', 'Golestan'), ('gil', 'Gilan'), ('lor', 'Lorestan'), ('maz', 'Mazandaran'), ('mrk', 'Markazi'), ('hrm', 'Hormozgan'), ('hmd', 'Hamedan'), ('yzd', 'Yazd')], max_length=7, verbose_name='Province')),
                ('city', models.CharField(max_length=40, verbose_name='city')),
                ('address', models.TextField(max_length=100, verbose_name='adderess')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_products', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_products', to='shoes.product')),
            ],
            options={
                'verbose_name_plural': 'Order-products',
            },
        ),
    ]
