# Generated by Django 4.2.3 on 2023-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=70),
        ),
    ]
