# Generated by Django 4.2.3 on 2023-07-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name_plural': 'ProductSizes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='shoes.category'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='availability_count',
            field=models.IntegerField(),
        ),
    ]
