# Generated by Django 4.2.3 on 2023-08-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('restore_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'AvailableQuantitys',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AvailableQuantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='shoes.product', verbose_name='product'),
        ),
    ]
