# Generated by Django 4.2.3 on 2023-07-19 08:00

from django.db import migrations, models
import shoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='back',
            field=models.ImageField(blank=True, default='', null=True, upload_to=shoes.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='front',
            field=models.ImageField(blank=True, default='', null=True, upload_to=shoes.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='left_side',
            field=models.ImageField(blank=True, default='', null=True, upload_to=shoes.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='right_side',
            field=models.ImageField(blank=True, default='', null=True, upload_to=shoes.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='up',
            field=models.ImageField(blank=True, default='', null=True, upload_to=shoes.models.product_image_upload_path),
        ),
    ]
