# Generated by Django 4.2.3 on 2023-08-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_gallery_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-create_timestamp',), 'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='created_at',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='updated_at',
            new_name='modify_timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='color',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='price',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='size',
            name='restore_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='AvailableQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('restore_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_quantity', to='shoes.product', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'AvailableQuantitys',
            },
        ),
    ]
