# Generated by Django 4.2.3 on 2023-08-03 01:13

from django.db import migrations, models
import shoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_product_color_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': ('Products',)},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=shoes.models.Product.get_upload_path),
        ),
    ]
