# Generated by Django 4.2.3 on 2023-08-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_quantity_product_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Quantities'},
        ),
    ]
