# Generated by Django 4.2.3 on 2023-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.IntegerField(choices=[(1, ' ADULT'), (2, 'TEENAGER '), (3, 'KIDS')], default=2),
        ),
    ]
