# Generated by Django 4.2.3 on 2023-08-05 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 39, 44, 275665, tzinfo=datetime.timezone.utc)),
        ),
    ]
