# Generated by Django 4.2.3 on 2023-08-02 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 9, 24, 20, 960697, tzinfo=datetime.timezone.utc)),
        ),
    ]
