# Generated by Django 4.2.3 on 2023-08-01 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 5, 54, 18, 420398, tzinfo=datetime.timezone.utc)),
        ),
    ]
