# Generated by Django 4.2.3 on 2023-08-06 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 9, 39, 18, 905891, tzinfo=datetime.timezone.utc)),
        ),
    ]
