# Generated by Django 4.2.3 on 2023-08-17 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 1, 35, 1, 558839, tzinfo=datetime.timezone.utc)),
        ),
    ]
