# Generated by Django 4.2.3 on 2023-08-19 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 6, 35, 33, 637684, tzinfo=datetime.timezone.utc)),
        ),
    ]
