# Generated by Django 4.2.3 on 2023-08-20 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0010_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 6, 22, 19, 458434, tzinfo=datetime.timezone.utc)),
        ),
    ]
