# Generated by Django 4.2.3 on 2023-08-20 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0011_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 18, 36, 2, 949261, tzinfo=datetime.timezone.utc)),
        ),
    ]
