# Generated by Django 4.2.3 on 2023-08-22 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0012_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 10, 12, 5, 205799, tzinfo=datetime.timezone.utc)),
        ),
    ]
