# Generated by Django 4.2.3 on 2023-08-26 11:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0014_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 11, 59, 47, 477327, tzinfo=datetime.timezone.utc)),
        ),
    ]
