# Generated by Django 4.2.3 on 2023-08-27 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0016_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 9, 3, 23, 325995, tzinfo=datetime.timezone.utc)),
        ),
    ]
