# Generated by Django 4.2.3 on 2023-08-27 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0017_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 15, 40, 58, 647502, tzinfo=datetime.timezone.utc)),
        ),
    ]
