# Generated by Django 4.2.3 on 2023-08-31 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0018_alter_otprequest_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 14, 40, 58, 57178, tzinfo=datetime.timezone.utc)),
        ),
    ]
